# GenerateEmbeddedConfig.ps1 — reads .env, writes EmbeddedConfig.Generated.cs
param([string]$ProjectDir = $PSScriptRoot)

# Fix: %~dp0 includes a trailing backslash; strip stray chars
$ProjectDir = $ProjectDir.TrimEnd('"').TrimEnd('\').TrimEnd('"').TrimEnd('.')

$envFile = Join-Path $ProjectDir ".env"
$outFile = Join-Path $ProjectDir "Utils\EmbeddedConfig.Generated.cs"

$cfg = @{
    GITHUB_API_KEY_PAT      = ""
    GITHUB_API_KEY_CLASSIC  = ""
    STEAM_WEB_API_KEY       = ""
    STEAM_CDN_TOKEN         = ""
    STEAM_SHARED_SECRET     = ""
    STEAM_IDENTITY_SECRET   = ""
    STEAM_REFRESH_TOKEN     = ""
    DEFAULT_CDN_REGION      = ""
    DEFAULT_WORKERS         = "32"
    APP_VERSION             = "1.5.0"
}

if (Test-Path $envFile) {
    Write-Host "[env] Reading .env..." -ForegroundColor Cyan
    Get-Content $envFile | ForEach-Object {
        $line = $_.Trim()
        if ($line -and -not $line.StartsWith("#")) {
            $idx = $line.IndexOf("=")
            if ($idx -gt 0) {
                $k = $line.Substring(0, $idx).Trim()
                $v = $line.Substring($idx + 1).Trim()
                if ($cfg.ContainsKey($k)) { $cfg[$k] = $v }
            }
        }
    }
    Write-Host "[env] Loaded .env" -ForegroundColor Green
} else {
    Write-Host "[env] WARNING: .env not found — building with empty keys. Copy .env.template to .env." -ForegroundColor Yellow
}

$cdnLine = "null"
if ($cfg.DEFAULT_CDN_REGION -match '^\d+$') {
    $cdnLine = "(int?)$($cfg.DEFAULT_CDN_REGION)"
}

$workers = 32
[int]::TryParse($cfg.DEFAULT_WORKERS, [ref]$workers) | Out-Null
if ($workers -le 0) { $workers = 32 }

function Escape([string]$s) { $s.Replace("\", "\\").Replace('"', '\"') }

$ts = Get-Date -Format "yyyy-MM-dd HH:mm:ss"

$tokenCount = @($cfg.GITHUB_API_KEY_PAT, $cfg.GITHUB_API_KEY_CLASSIC) | Where-Object { $_ -ne "" } | Measure-Object | Select-Object -ExpandProperty Count
if ($tokenCount -gt 0) {
    Write-Host "[env] GitHub: $tokenCount token(s) loaded ($($tokenCount * 5000) req/hr capacity)" -ForegroundColor Cyan
} else {
    Write-Host "[env] GitHub: no tokens — anonymous mode (60 req/hr). Add tokens to .env for full speed." -ForegroundColor Yellow
}

$content = @"
// AUTO-GENERATED by GenerateEmbeddedConfig.ps1 on $ts
// DO NOT EDIT — overwritten on every build from .env
namespace LustsDepotDownloaderPro.Utils;
public static partial class EmbeddedConfig
{
    static EmbeddedConfig()
    {
        _GitHubApiKeyPat     = "$(Escape $cfg.GITHUB_API_KEY_PAT)";
        _GitHubApiKeyClassic = "$(Escape $cfg.GITHUB_API_KEY_CLASSIC)";
        _SteamWebApiKey      = "$(Escape $cfg.STEAM_WEB_API_KEY)";
        _SteamCdnToken       = "$(Escape $cfg.STEAM_CDN_TOKEN)";
        _SteamSharedSecret   = "$(Escape $cfg.STEAM_SHARED_SECRET)";
        _SteamIdentitySecret = "$(Escape $cfg.STEAM_IDENTITY_SECRET)";
        _SteamRefreshToken   = "$(Escape $cfg.STEAM_REFRESH_TOKEN)";
        _DefaultCdnRegion    = $cdnLine;
        _DefaultWorkers      = $workers;
        _AppVersion          = "$(Escape $cfg.APP_VERSION)";
    }
}
"@

$outDir = Split-Path $outFile -Parent
if (-not (Test-Path $outDir)) { New-Item -ItemType Directory -Path $outDir -Force | Out-Null }

$content | Set-Content -Path $outFile -Encoding UTF8
Write-Host "[env] Generated: $outFile" -ForegroundColor Green

# Patch version in csproj
if ($cfg.APP_VERSION -ne "") {
    $csproj = Join-Path $ProjectDir "LustsDepotDownloaderPro.csproj"
    if (Test-Path $csproj) {
        $xml = Get-Content $csproj -Raw
        $newXml = $xml -replace '<Version>[^<]*</Version>', "<Version>$($cfg.APP_VERSION)</Version>"
        if ($newXml -ne $xml) {
            Set-Content -Path $csproj -Value $newXml -Encoding UTF8 -NoNewline
        }
    }
}
