#!/usr/bin/env bash
set -e
PROJECT_DIR="${1:-$(dirname "$0")}"
PROJECT_DIR="${PROJECT_DIR%/}"   # strip trailing slash
ENV_FILE="$PROJECT_DIR/.env"
OUT_FILE="$PROJECT_DIR/Utils/EmbeddedConfig.Generated.cs"

GITHUB_API_KEY_PAT="" GITHUB_API_KEY_CLASSIC=""
STEAM_WEB_API_KEY="" STEAM_CDN_TOKEN=""
STEAM_SHARED_SECRET="" STEAM_IDENTITY_SECRET="" STEAM_REFRESH_TOKEN=""
DEFAULT_CDN_REGION="" DEFAULT_WORKERS="32" APP_VERSION="1.5.0"

if [ -f "$ENV_FILE" ]; then
    echo "[env] Reading .env..."
    while IFS= read -r line || [[ -n "$line" ]]; do
        line="${line%%#*}"; line="${line// /}"
        [ -z "$line" ] && continue
        k="${line%%=*}"; v="${line#*=}"
        case "$k" in
            GITHUB_API_KEY_PAT)     GITHUB_API_KEY_PAT="$v" ;;
            GITHUB_API_KEY_CLASSIC) GITHUB_API_KEY_CLASSIC="$v" ;;
            STEAM_WEB_API_KEY)      STEAM_WEB_API_KEY="$v" ;;
            STEAM_CDN_TOKEN)        STEAM_CDN_TOKEN="$v" ;;
            STEAM_SHARED_SECRET)    STEAM_SHARED_SECRET="$v" ;;
            STEAM_IDENTITY_SECRET)  STEAM_IDENTITY_SECRET="$v" ;;
            STEAM_REFRESH_TOKEN)    STEAM_REFRESH_TOKEN="$v" ;;
            DEFAULT_CDN_REGION)     DEFAULT_CDN_REGION="$v" ;;
            DEFAULT_WORKERS)        DEFAULT_WORKERS="$v" ;;
            APP_VERSION)            APP_VERSION="$v" ;;
        esac
    done < "$ENV_FILE"
    echo "[env] Loaded .env"
else
    echo "[env] WARNING: .env not found — building with empty keys."
fi

CDN_LINE="null"
[[ "$DEFAULT_CDN_REGION" =~ ^[0-9]+$ ]] && CDN_LINE="(int?)$DEFAULT_CDN_REGION"
WORKERS=32
[[ "$DEFAULT_WORKERS" =~ ^[0-9]+$ ]] && [ "$DEFAULT_WORKERS" -gt 0 ] && WORKERS="$DEFAULT_WORKERS"
escape() { echo "$1" | sed 's/\\/\\\\/g' | sed 's/"/\\"/g'; }
TS=$(date '+%Y-%m-%d %H:%M:%S')

mkdir -p "$(dirname "$OUT_FILE")"
cat > "$OUT_FILE" << EOF
// AUTO-GENERATED by GenerateEmbeddedConfig.sh on $TS
// DO NOT EDIT — overwritten on every build from .env
namespace LustsDepotDownloaderPro.Utils;
public static partial class EmbeddedConfig
{
    static EmbeddedConfig()
    {
        _GitHubApiKeyPat     = "$(escape "$GITHUB_API_KEY_PAT")";
        _GitHubApiKeyClassic = "$(escape "$GITHUB_API_KEY_CLASSIC")";
        _SteamWebApiKey      = "$(escape "$STEAM_WEB_API_KEY")";
        _SteamCdnToken       = "$(escape "$STEAM_CDN_TOKEN")";
        _SteamSharedSecret   = "$(escape "$STEAM_SHARED_SECRET")";
        _SteamIdentitySecret = "$(escape "$STEAM_IDENTITY_SECRET")";
        _SteamRefreshToken   = "$(escape "$STEAM_REFRESH_TOKEN")";
        _DefaultCdnRegion    = $CDN_LINE;
        _DefaultWorkers      = $WORKERS;
        _AppVersion          = "$(escape "$APP_VERSION")";
    }
}
EOF
echo "[env] Generated: $OUT_FILE"
